# Generated by Django 4.1 on 2023-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobNum', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('emailId', models.EmailField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('aniversary', models.DateField(blank=True)),
                ('customerNote', models.TextField(blank=True)),
                ('dummy1', models.IntegerField(blank=True)),
                ('profilePic', models.FileField(blank=True, upload_to='profilePic/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
